title: <p align="center"> SHASHEESH RANE </p>
logo: /assets/img/DP.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shasheesh/">LinkedIn</a> |
  <a href="https://github.com/shasheeshrane">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
    Working in Telecom domain for 13 years.
  <br>
  </p>



theme: jekyll-theme-minimal
